name = "AbstractGSBPs"
uuid = "cb3d5aec-0da4-4bd1-bdcb-5a67dc07bef0"
authors = ["Iván Gutiérrez"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
